// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class AppUser
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public string PasswordAlg { get; set; }

    public int? PasswordIters { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Assessment> AssessmentCreatedByUsers { get; set; } = new List<Assessment>();

    public virtual ICollection<Assessment> AssessmentUpdatedByUsers { get; set; } = new List<Assessment>();

    public virtual ICollection<Attendance> AttendanceCreatedByUsers { get; set; } = new List<Attendance>();

    public virtual ICollection<Attendance> AttendanceUpdatedByUsers { get; set; } = new List<Attendance>();

    public virtual ICollection<ClassSection> ClassSectionCreatedByUsers { get; set; } = new List<ClassSection>();

    public virtual ICollection<ClassSection> ClassSectionUpdatedByUsers { get; set; } = new List<ClassSection>();

    public virtual ICollection<Course> CourseCreatedByUsers { get; set; } = new List<Course>();

    public virtual ICollection<Course> CourseUpdatedByUsers { get; set; } = new List<Course>();

    public virtual AppUser CreatedByUser { get; set; }

    public virtual ICollection<Enrollment> EnrollmentCreatedByUsers { get; set; } = new List<Enrollment>();

    public virtual ICollection<Enrollment> EnrollmentUpdatedByUsers { get; set; } = new List<Enrollment>();

    public virtual ICollection<Grade> GradeCreatedByUsers { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeUpdatedByUsers { get; set; } = new List<Grade>();

    public virtual ICollection<Guardian> GuardianCreatedByUsers { get; set; } = new List<Guardian>();

    public virtual ICollection<Guardian> GuardianUpdatedByUsers { get; set; } = new List<Guardian>();

    public virtual Guardian GuardianUser { get; set; }

    public virtual ICollection<AppUser> InverseCreatedByUser { get; set; } = new List<AppUser>();

    public virtual ICollection<AppUser> InverseUpdatedByUser { get; set; } = new List<AppUser>();

    public virtual ICollection<Role> RoleCreatedByUsers { get; set; } = new List<Role>();

    public virtual ICollection<Role> RoleUpdatedByUsers { get; set; } = new List<Role>();

    public virtual ICollection<Staff> StaffCreatedByUsers { get; set; } = new List<Staff>();

    public virtual ICollection<Staff> StaffUpdatedByUsers { get; set; } = new List<Staff>();

    public virtual Staff StaffUser { get; set; }

    public virtual ICollection<Student> StudentCreatedByUsers { get; set; } = new List<Student>();

    public virtual ICollection<StudentGuardian> StudentGuardianCreatedByUsers { get; set; } = new List<StudentGuardian>();

    public virtual ICollection<StudentGuardian> StudentGuardianUpdatedByUsers { get; set; } = new List<StudentGuardian>();

    public virtual ICollection<Student> StudentUpdatedByUsers { get; set; } = new List<Student>();

    public virtual Student StudentUser { get; set; }

    public virtual ICollection<Term> TermCreatedByUsers { get; set; } = new List<Term>();

    public virtual ICollection<Term> TermUpdatedByUsers { get; set; } = new List<Term>();

    public virtual AppUser UpdatedByUser { get; set; }

    public virtual ICollection<UserRole> UserRoleCreatedByUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUpdatedByUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();
}