// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class Assessment
{
    public int AssessmentId { get; set; }

    public int SectionId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal MaxPoints { get; set; }

    public decimal? WeightPercent { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ClassSection Section { get; set; }
}