// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class Attendance
{
    public int AttendanceId { get; set; }

    public int SectionId { get; set; }

    public int StudentId { get; set; }

    public DateTime AttendanceDate { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public DateTime RecordedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ClassSection Section { get; set; }

    public virtual Student Student { get; set; }
}