// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class ClassSection
{
    public int SectionId { get; set; }

    public int CourseId { get; set; }

    public int TermId { get; set; }

    public string SectionCode { get; set; }

    public int TeacherId { get; set; }

    public int? Capacity { get; set; }

    public string ScheduleInfo { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Assessment> Assessments { get; set; } = new List<Assessment>();

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Course Course { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual Staff Teacher { get; set; }

    public virtual Term Term { get; set; }
}