// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class Enrollment
{
    public int EnrollmentId { get; set; }

    public int StudentId { get; set; }

    public int SectionId { get; set; }

    public DateTime EnrollDate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual AppUser CreatedByUser { get; set; }

    public virtual ClassSection Section { get; set; }

    public virtual Student Student { get; set; }

    public virtual AppUser UpdatedByUser { get; set; }
}