// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class Grade
{
    public int GradeId { get; set; }

    public int AssessmentId { get; set; }

    public int StudentId { get; set; }

    public decimal PointsEarned { get; set; }

    public DateTime GradedAtUtc { get; set; }

    public string Feedback { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual AppUser CreatedByUser { get; set; }

    public virtual Student Student { get; set; }

    public virtual AppUser UpdatedByUser { get; set; }
}