// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SMS.Entities.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SMS.Entities.Models
{
    public partial interface ISmsContextProcedures
    {
        Task<List<usp_AssignRoleResult>> usp_AssignRoleAsync(int? userId, string roleName, int? createdByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_CreateUserResult>> usp_CreateUserAsync(string username, string email, string phone, byte[] passwordHash, byte[] passwordSalt, string passwordAlg, int? passwordIters, int? createdByUserId, OutputParameter<int?> newUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_LinkUserToGuardianResult>> usp_LinkUserToGuardianAsync(int? userId, int? guardianId, int? updatedByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_LinkUserToStaffResult>> usp_LinkUserToStaffAsync(int? userId, int? staffId, int? updatedByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_LinkUserToStudentResult>> usp_LinkUserToStudentAsync(int? userId, int? studentId, int? updatedByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
