// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class StudentGuardian
{
    public int StudentGuardianId { get; set; }

    public int StudentId { get; set; }

    public int GuardianId { get; set; }

    public string Relationship { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual AppUser CreatedByUser { get; set; }

    public virtual Guardian Guardian { get; set; }

    public virtual Student Student { get; set; }

    public virtual AppUser UpdatedByUser { get; set; }
}