// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string RollNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? Dob { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public bool IsActive { get; set; }

    public int? UserId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual AppUser CreatedByUser { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ICollection<StudentGuardian> StudentGuardians { get; set; } = new List<StudentGuardian>();

    public virtual AppUser UpdatedByUser { get; set; }

    public virtual AppUser User { get; set; }
}