// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMS.Entities.Models
{
    public partial class usp_AssignRoleResult
    {
        public int UserId { get; set; }
        [StringLength(100)]
        public string Username { get; set; }
        public int RoleId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}
