// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMS.Entities.Models
{
    public partial class usp_CreateUserResult
    {
        public int UserId { get; set; }
        [StringLength(100)]
        public string Username { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        [StringLength(40)]
        public string PasswordAlg { get; set; }
        public int? PasswordIters { get; set; }
        public bool IsActive { get; set; }
        public DateTime? LastLoginAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public int? CreatedByUserId { get; set; }
        public int? UpdatedByUserId { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
