// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMS.Entities.Models
{
    public partial class usp_LinkUserToStaffResult
    {
        public int StaffId { get; set; }
        [StringLength(20)]
        public string StaffCode { get; set; }
        public int? UserId { get; set; }
    }
}
