// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS.Entities.Models;

public partial class VwUserPersonLink
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Roles { get; set; }

    public int? StudentId { get; set; }

    public string RollNumber { get; set; }

    public int? GuardianId { get; set; }

    public int? StaffId { get; set; }

    public string StaffCode { get; set; }
}